### ISSUE TITLE
Will this be available in enlish

### ISSUE THREAD

**Issue by shoubhik** [horance-liu/tensorflow-internals#2]
Will the text be available in English?

**Comment by sergey-serebryakov** [comment]
I have a [version](https://github.com/sergey-serebryakov/tensorflow-internals) that was translated semi-automatically with google translate.  Needs careful proof-reading, but can be used in its current state.

**Comment by shoubhik** [comment]
Thanks, @sergey-serebryakov. This will be of great help.

**Comment by horance-liu** [comment]
@sergey-serebryakov Thank you. I will update it to TensorFlow 2.0 in 2019.
