### ISSUE TITLE
Is this out of date? current version is 1.12.

### ISSUE THREAD

**Issue by oneTaken** [horance-liu/tensorflow-internals#3]
This book is based on tf 1.2?
There are a lot of big changes between this version and current version.
Right?

**Comment by zakizhou** [comment]
I believe lots of python api  have changed (mainly because 2.0 will be released and traditional graph execution will be deprecated)but the internal c++ classes and function haven't, so you can still rely on this book  to learn tensorflow internal

**Comment by oneTaken** [comment]
Emm, learning the internal C++ classes is really a cost of time. It's not easy.  If there will be not enough pay back,  it's really heart-hurting.

**Comment by zakizhou** [comment]
Well, I agree, but I think whether to dive into the core of tensorflow depends on what you want, if you only what to do some ML/DL applications, then you need not to.
