### ISSUE TITLE
session的前后端交互为何需要一个中间的C接口层？

### ISSUE THREAD

**Issue by xiaobaoding** [horance-liu/tensorflow-internals#7]
![image](https://user-images.githubusercontent.com/4554417/50432206-24e83a00-090b-11e9-8352-a4b8520ce659.png)
在看第二部分：系统架构的第五章《C API:分水岭》，讲session的前后端交互流程中，python前端和最终实现的C++之间，有一层C API接口。想了解下这一层的设计是有什么目的或者作用的？

**Comment by horance-liu** [comment]
几乎所有跨语言系统调用，c是最好的桥梁。例如，Python调用C或C++，中间桥梁C是最方便的。
